version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: simple-douyin-postgres
    restart: always
    environment:
      POSTGRES_USER: simple_douyin
      POSTGRES_PASSWORD: 1qaz0plm
      POSTGRES_DB: simple_douyin_db
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: simple-douyin-redis
    restart: always
    environment:
      REDIS_PASSWORD: 1qaz0plm
    expose:
      - "6379"
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data

  etcd:
    image: bitnami/etcd:latest
    container_name: simple-douyin-etcd
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    expose:
      - "2379"
      - "2380"
    # ports:
    #   - "2379:2379"
    #   - "2380:2380"
    volumes:
      - etcd_data:/bitnami

  sakura-frp: # frp port 18080 for use
    image: natfrp/frpc:latest
    container_name: simple-douyin-frp
    restart: always
    command: '-f lc28c5p96ar95kgga6hkxx9vpifksqai:10415888 --remote_control 7203223kjl'

  simple-douyin:
    image: jscblack/simple-douyin:latest
    container_name: simple-douyin-main
    restart: always
    ports:
      - "18080:8888"
    
  prometheus:
    image: prom/prometheus:latest
    container_name: simple-douyin-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - '9090'
  
  grafana:
    image: grafana/grafana:latest
    container_name: simple-douyin-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - '13000:3000'

volumes:
  postgres_data:
  redis_data:
  etcd_data:
  grafana_data:
  prometheus_data: